# Generated by Django 5.1.2 on 2024-10-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapp', '0002_student_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classdata',
        ),
    ]
