# Generated by Django 5.1.2 on 2024-10-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapp', '0003_delete_classdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='classdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.FileField(blank=True, null=True, upload_to='resource/')),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_material', to='classroomapp.googleclass')),
            ],
        ),
    ]
